import styled from 'styled-components';

export const Wrapper = styled.div.attrs(() => ({
    className: 'container border',
}))`


    text-decoration: none !important;
    background-color: #ededed;

    -webkit-box-shadow: 0px 6px 9px -1px rgba(0,0,0,0.70); 
    box-shadow: 0px 6px 9px -1px rgba(0,0,0,0.70);
    -webkit-animation: slide-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    animation: slide-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;

    /* ----------------------------------------------
    * Generated by Animista on 2022-1-24 18:43:39
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation slide-bottom
    * ----------------------------------------
    */
    @-webkit-keyframes slide-bottom {
        0% {
            -webkit-transform: translateY(0);
                    transform: translateY(0);
        }
        100% {
            -webkit-transform: translateY(100px);
                    transform: translateY(100px);
        }
    }
    @keyframes slide-bottom {
        0% {
            -webkit-transform: translateY(0);
                    transform: translateY(0);
        }
        100% {
            -webkit-transform: translateY(100px);
                    transform: translateY(100px);
        }
    }

`;

export const Content = styled.div`
    padding: 20px;
    max-width: 100%;
`;
